classdef bh_fd_node_type_ENUM 
   enumeration
        G_BLK_B_INTERNAL
        G_BLK_B_NW
        G_BLK_B_N
        G_BLK_B_NE
        G_BLK_B_E
        G_BLK_B_SE
        G_BLK_B_S
        G_BLK_B_SW
        G_BLK_B_W
        %---------------------------
        G_BLK_C_INTERNAL
        G_BLK_C_W
        G_BLK_C_NW
        G_BLK_C_N
        G_BLK_C_NE
        G_BLK_C_E
        G_BLK_C_SE
        G_BLK_C_S
        %---------------------------
        G_BLK_A_INTERNAL
        G_BLK_A_SW
        G_BLK_A_W
        G_BLK_A_S
        G_BLK_A_SE
        G_BLK_A_E   
   end
end